global:
  scrape_interval: 10s
  scrape_timeout: 9s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets:
          - "prometheus:9090"